version: "3"

services:
  backend:
    image: caltuntas/poc-contract-management
    build: .
    container_name: poc-contract-management
    ports:
      - 8080:8080
  frontend:
    image: caltuntas/poc-contract-management-ui
    build: .
    container_name: poc-contract-management-ui
    environment:
      NODE_ENV: production
    ports:
      - 80:80

  etherpad:
    image: etherpad/etherpad
    container_name: poc-contract-management-etherpad
    ports:
      - 9001:9001